# prepare_model.py
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
import pickle

# Sample dataset
data = [
    ("I love this product!", "positive"),
    ("This is the best thing ever.", "positive"),
    ("Absolutely fantastic!", "positive"),
    ("I am very happy with this.", "positive"),
    ("Excellent quality and great value.", "positive"),
    ("Highly recommend this.", "positive"),
    ("I am extremely satisfied.", "positive"),
    ("A wonderful experience.", "positive"),
    ("Top-notch service!", "positive"),
    ("Great job!", "positive"),
    ("I hate this product!", "negative"),
    ("This is the worst thing ever.", "negative"),
    ("Absolutely terrible!", "negative"),
    ("I am very unhappy with this.", "negative"),
    ("Poor quality and overpriced.", "negative"),
    ("Not recommended at all.", "negative"),
    ("I am extremely dissatisfied.", "negative"),
    ("A horrible experience.", "negative"),
    ("Terrible service!", "negative"),
    ("Bad job!", "negative"),
    ("Very pleased with the purchase.", "positive"),
    ("This is not bad at all.", "positive"),
    ("I enjoyed using this.", "positive"),
    ("Quite good actually.", "positive"),
    ("This meets my expectations.", "positive"),
    ("Not the best, but good.", "positive"),
    ("I can see why people like it.", "positive"),
    ("Satisfied with the results.", "positive"),
    ("Quality is quite good.", "positive"),
    ("Nice product.", "positive"),
    ("This did not work as expected.", "negative"),
    ("I am not pleased with this.", "negative"),
    ("Disappointed with the quality.", "negative"),
    ("Not worth the money.", "negative"),
    ("I do not recommend this.", "negative"),
    ("This is below expectations.", "negative"),
    ("Unsatisfactory experience.", "negative"),
    ("Poor performance.", "negative"),
    ("This is not what I wanted.", "negative"),
    ("Will not buy this again.", "negative"),
    ("I am very happy with this service.", "positive"),
    ("This is fantastic!", "positive"),
    ("Great value for money.", "positive"),
    ("Superb quality!", "positive"),
    ("Very good and reliable.", "positive"),
    ("I am satisfied with this.", "positive"),
    ("A great choice.", "positive"),
    ("Totally worth it.", "positive"),
    ("Wonderful product.", "positive"),
    ("This is very bad.", "negative"),
    ("I am extremely unhappy.", "negative"),
    ("Terrible quality.", "negative"),
    ("Not worth the time.", "negative"),
    ("I do not like this.", "negative"),
    ("This is a waste of money.", "negative"),
    ("Unhappy with the results.", "negative"),
    ("This did not meet expectations.", "negative"),
    ("Poorly made.", "negative"),
    ("I would not recommend this.", "negative"),
    ("This is a bad product.", "negative"),
    ("I am very pleased with this.", "positive"),
    ("This is excellent!", "positive"),
    ("Good value for money.", "positive"),
    ("High quality product.", "positive"),
    ("Very reliable and good.", "positive"),
    ("I am happy with this.", "positive"),
    ("A good choice.", "positive"),
    ("Well worth it.", "positive"),
    ("Good product.", "positive"),
    ("This is terrible.", "negative"),
    ("I am extremely dissatisfied.", "negative"),
    ("Low quality.", "negative"),
    ("Not worth the effort.", "negative"),
    ("I dislike this.", "negative"),
    ("This is a waste of time.", "negative"),
    ("Unsatisfied with the results.", "negative"),
    ("This did not meet my expectations.", "negative"),
    ("Poorly designed.", "negative"),
    ("I would not recommend this to anyone.", "negative"),
    ("This is a bad service.", "negative"),
    ("I am very satisfied with this.", "positive"),
    ("This is great!", "positive"),
    ("Fair value for money.", "positive"),
    ("Good quality product.", "positive"),
    ("Very good and reliable service.", "positive"),
    ("I am satisfied with this service.", "positive"),
    ("A good option.", "positive"),
    ("Worth every penny.", "positive"),
    ("Good service.", "positive"),
    ("This is awful.", "negative"),
    ("I am extremely disappointed.", "negative"),
    ("Very low quality.", "negative"),
    ("Not worth the investment.", "negative"),
    ("I hate this.", "negative"),
    ("This is a complete waste of time.", "negative"),
    ("Very unhappy with the results.", "negative"),
    ("This did not meet my standards.", "negative"),
    ("Poorly executed.", "negative"),
    ("I would not recommend this to anyone.", "negative"),
    ("This is a terrible service.", "negative"),
    ("I am very happy with this.", "positive"),
    ("This is fantastic!", "positive"),
    ("Good value for the price.", "positive"),
    ("High-quality product.", "positive"),
    ("Very reliable and excellent service.", "positive"),
    ("I am happy with this service.", "positive"),
    ("A great choice.", "positive"),
    ("Well worth the investment.", "positive"),
    ("Excellent service.", "positive"),
    ("This is horrible.", "negative"),
    ("I am extremely unhappy.", "negative"),
    ("Low-quality product.", "negative"),
    ("Not worth the cost.", "negative"),
    ("I dislike this service.", "negative"),
    ("This is a complete waste of money.", "negative"),
    ("Unhappy with the results.", "negative"),
    ("This did not meet my needs.", "negative"),
    ("Poorly designed product.", "negative"),
    ("I would not recommend this.", "negative"),
    ("This is a bad product.", "negative"),
    ("I am very pleased with this.", "positive"),
    ("This is amazing!", "positive"),
    ("Fair price for the quality.", "positive"),
    ("High-quality service.", "positive"),
    ("Very reliable product.", "positive"),
    ("I am pleased with this service.", "positive"),
    ("A great option.", "positive"),
    ("Worth every cent.", "positive"),
    ("Good product.", "positive"),
    ("This is terrible.", "negative"),
    ("I am extremely dissatisfied.", "negative"),
    ("Low-quality service.", "negative"),
    ("Not worth the price.", "negative"),
    ("I hate this product.", "negative"),
    ("This is a complete waste of resources.", "negative"),
    ("Unhappy with the experience.", "negative"),
    ("This did not meet my expectations.", "negative"),
    ("Poorly made product.", "negative"),
    ("I would not suggest this.", "negative"),
    ("This is a bad service.", "negative"),
    ("I am very satisfied with this.", "positive"),
    ("This is incredible!", "positive"),
    ("Good value for the money.", "positive"),
    ("High-quality experience.", "positive"),
    ("Very reliable company.", "positive"),
    ("I am satisfied with this service.", "positive"),
    ("A great investment.", "positive"),
    ("Well worth the money.", "positive"),
    ("Good choice.", "positive"),
    ("This is awful.", "negative"),
    ("I am extremely disappointed.", "negative"),
    ("Low-quality experience.", "negative"),
    ("Not worth the investment.", "negative"),
    ("I dislike this product.", "negative"),
    ("This is a complete waste of time.", "negative"),
    ("Unhappy with the outcome.", "negative"),
    ("This did not meet my standards.", "negative"),
    ("Poorly designed service.", "negative"),
    ("I would not recommend this company.", "negative"),
    ("This is a bad choice.", "negative"),
    ("I am very happy with this.", "positive"),
    ("This is fantastic!", "positive"),
    ("Fair value for the price.", "positive"),
    ("High-quality product.", "positive"),
    ("Very reliable service.", "positive"),
    ("I am happy with this service.", "positive"),
    ("A great purchase.", "positive"),
    ("Worth every penny.", "positive"),
    ("Good decision.", "positive"),
    ("This is terrible.", "negative"),
    ("I am extremely unhappy.", "negative"),
    ("Low-quality product.", "negative"),
    ("Not worth the cost.", "negative"),
    ("I hate this service.", "negative"),
    ("This is a complete waste of money.", "negative"),
    ("Unhappy with the result.", "negative"),
    ("This did not meet my needs.", "negative"),
    ("Poorly made service.", "negative"),
    ("I would not suggest this company.", "negative"),
    ("This is a bad investment.", "negative"),
    ("I am very pleased with this.", "positive"),
    ("This is amazing!", "positive"),
    ("Good value for the price.", "positive"),
    ("High-quality experience.", "positive"),
    ("Very reliable product.", "positive"),
    ("I am pleased with this service.", "positive"),
    ("A great buy.", "positive"),
    ("Well worth the cost.", "positive"),
    ("Good selection.", "positive"),
    ("This is horrible.", "negative"),
    ("I am extremely dissatisfied.", "negative"),
    ("Low-quality experience.", "negative"),
    ("Not worth the money.", "negative"),
    ("I dislike this service.", "negative"),
    ("This is a complete waste of resources.", "negative"),
    ("Unhappy with the outcome.", "negative"),
    ("This did not meet my expectations.", "negative"),
    ("Poorly designed product.", "negative"),
    ("I would not recommend this service.", "negative"),
    ("This is a bad choice.", "negative"),
    ("I am very satisfied with this.", "positive"),
    ("This is excellent!", "positive"),
    ("Fair price for the quality.", "positive"),
    ("High-quality service.", "positive"),
    ("Very reliable company.", "positive"),
    ("I am satisfied with this service.", "positive"),
    ("A great investment.", "positive"),
    ("Well worth the investment.", "positive"),
    ("Good quality.", "positive"),
    
]

# Convert to DataFrame
df = pd.DataFrame(data, columns=["text", "sentiment"])

# Split the data
X = df["text"]
y = df["sentiment"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a pipeline
model = make_pipeline(CountVectorizer(), MultinomialNB())

# Train the model
model.fit(X_train, y_train)

# Save the model
with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model training complete and saved as model.pkl")
